name: A workflow to build books using Enki
on: [workflow_dispatch]
jobs:
  build:
    name: Build book
    runs-on: ubuntu-latest
    container: openstax/enki:20220922.225409
    permissions:
      deployments: write
      packages: write
      contents: write
    steps:
      - name: Set Env variables
        run: |
          echo "TAG=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV
          echo "WORKDIR=/__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls -alt ${{ env.WORKDIR }}
      - name: Build Book
        run: |
          echo 'Initializing Book Build'
          cd /github
          git clone https://github.com/openstax/enki
          cd enki
          git checkout sk-epub-fixes 
          TRACE_ON=1 LOCAL_ATTIC_DIR=_attic TERM=xterm /github/enki/dockerfiles/enki-in-container --command all-git-epub --repo-dir ${{ env.WORKDIR }} --style dummy


      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          custom_tag: ${{ env.TAG }}
          tag_prefix: ""
          release_branches: ${GITHUB_REF##*/}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: /tmp/_attic/IO_ARTIFACTS/programming-fundamentals-a-modular-structured-approach.epub
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          omitBody: True
